### ISSUE TITLE
System.ComponentModel.Win32Exception (8): Exec format error

### ISSUE THREAD

**Issue by itaims** [GildedHonour/OpenVpnManagement#2]
Hello,

we are trying to make App. But we are getting the following issue and don't why. 

> System.ComponentModel.Win32Exception (8): Exec format error
>    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at OpenVpnManagement.Manager.RunOpenVpnProcess()
>    at OpenVpnManagement.Manager..ctor(String host, Int32 port, String ovpnFileName, String userName, String password, String openVpnExeFileName)
>    at TizenApp.App.startOVPN() in Z:\Projects\TizenApp\TizenApp\TizenApp\TizenApp.cs:line 157
>    at TizenApp.App.GetLocalIPAddress() in Z:\Projects\TizenApp\TizenApp\TizenApp\TizenApp.cs:line 107
>    at TizenApp.App..ctor() in Z:\Projects\TizenApp\TizenApp\TizenApp\TizenApp.cs:line 134
>    at TizenApp.Program.OnCreate() in Z:\Projects\TizenApp\TizenApp\TizenApp.Wearable\TizenApp.Wearable.cs:line 11
>    at Tizen.Applications.CoreBackend.UICoreBackend.OnCreateNative(IntPtr data)
>    at Tizen.Applications.CoreBackend.UICoreBackend.Run(String[] args)
>    at Tizen.Applications.CoreApplication.Run(String[] args)
>    at Tizen.Applications.CoreUIApplication.Run(String[] args)
>    at TizenApp.Program.Main(String[] args) in Z:\Projects\TizenApp\TizenApp\TizenApp.Wearable\TizenApp.Wearable.cs:line 20 occurred

**Comment by GildedHonour** [comment]
That's not enough details
